#*****************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# user_top.tcl: Tcl script for re-creating project 'fos_a7_optic_fpga'
#
# Generated by Vivado on Thu Apr 20 09:33:53 +0800 2023
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (user_top.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "E:/git_test/zmy_study/KL7071/prj/fos_a7_optic_fpga/fos_a7_optic_fpga.srcs/sources_1/bd/design_1/design_1.bd"
#    "E:/git_test/zmy_study/KL7071/prj/fos_a7_optic_fpga/fos_a7_optic_fpga.srcs/sources_1/imports/hdl/design_1_wrapper.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    "E:/git_test/zmy_study/KL7071/rtl/xuji_wangbiao/RT_LAB_comm_with_MC.edf"
#    "E:/git_test/zmy_study/KL7071/rtl/sources_1/ip/ila_fault_debug/ila_fault_debug.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/ip/clk_wiz_125m/clk_wiz_125m.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/ip/fifo_512x33_dual_clk/fifo_512x33_dual_clk.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/ip/aurora_8b10b_gtp/aurora_8b10b_gtp.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/sources_1/ip/flash_fifo_8192X8/flash_fifo_8192X8.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/uart_app/async_230400.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/example_design_aurora_pkg/aurora_8b10b_gtp_cdc_sync_exdes.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_clock_module.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_gt_common_wrapper.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_support.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_support_reset_logic.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/aurora_app/aurora_app_s.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/uart_app/bp_uart_tx_rx_230400.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/auto_load_flash/flash_dri.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/auto_load_flash/flash_top.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/auto_load_flash/flash_update.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/fpga_top/led.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/fpga_top/rst_ctrl_high.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/fpga_top/rst_ctrl_high_gt.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/fpga_top/st_lc_fpga_top.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/uart_app/uart_app_s.v"
#    "E:/git_test/zmy_study/KL7071/rtl/xuji_wangbiao/RT_LAB_comm_with_MC.vhd"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/fpga_top/user_top.v"
#    "E:/git_test/zmy_study/KL7071/rtl/ip/vio_sel/vio_sel.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/auto_load_flash/ila_flash/ila_flash.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/ip/dpram_w512x32_r2048x8/dpram_w512x32_r2048x8.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/ip001_uart/uart_rx.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/ip001_uart/uart_top.v"
#    "E:/git_test/zmy_study/KL7071/rtl/imports/ip001_uart/uart_tx.v"
#    "E:/git_test/zmy_study/KL7071/rtl/sources_1/ip/ila_bp_uart/ila_bp_uart.xci"
#    "E:/git_test/zmy_study/KL7071/rtl/st_lc_fpga_top.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set project_name "fos_a7_optic_fpga"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set project_name $::user_project_name
}

variable script_file
set script_file "user_top.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set project_name [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../prj/fos_a7_optic_fpga"]"

# Create project
create_project ${project_name} ./${project_name} -part xc7a15tcsg325-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${project_name}.cache/ip" -objects $obj
set_property -name "part" -value "xc7a15tcsg325-2" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../rtl/xuji_wangbiao/RT_LAB_comm_with_MC.edf"]"\
 "[file normalize "$origin_dir/../rtl/sources_1/ip/ila_fault_debug/ila_fault_debug.xci"]"\
 "[file normalize "$origin_dir/../rtl/ip/clk_wiz_125m/clk_wiz_125m.xci"]"\
 "[file normalize "$origin_dir/../rtl/ip/fifo_512x33_dual_clk/fifo_512x33_dual_clk.xci"]"\
 "[file normalize "$origin_dir/../rtl/ip/aurora_8b10b_gtp/aurora_8b10b_gtp.xci"]"\
 "[file normalize "$origin_dir/../rtl/sources_1/ip/flash_fifo_8192X8/flash_fifo_8192X8.xci"]"\
 "[file normalize "$origin_dir/../rtl/imports/uart_app/async_230400.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/example_design_aurora_pkg/aurora_8b10b_gtp_cdc_sync_exdes.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_clock_module.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_gt_common_wrapper.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_support.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/example_design_aurora_pkg/support/aurora_8b10b_gtp_support_reset_logic.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/aurora_app/aurora_app_s.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/uart_app/bp_uart_tx_rx_230400.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/auto_load_flash/flash_dri.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/auto_load_flash/flash_top.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/auto_load_flash/flash_update.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/fpga_top/led.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/fpga_top/rst_ctrl_high.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/fpga_top/rst_ctrl_high_gt.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/fpga_top/st_lc_fpga_top.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/uart_app/uart_app_s.v"]"\
 "[file normalize "$origin_dir/../rtl/xuji_wangbiao/RT_LAB_comm_with_MC.vhd"]"\
 "[file normalize "$origin_dir/../rtl/imports/fpga_top/user_top.v"]"\
 "[file normalize "$origin_dir/../rtl/ip/vio_sel/vio_sel.xci"]"\
 "[file normalize "$origin_dir/../rtl/imports/auto_load_flash/ila_flash/ila_flash.xci"]"\
 "[file normalize "$origin_dir/../rtl/ip/dpram_w512x32_r2048x8/dpram_w512x32_r2048x8.xci"]"\
 "[file normalize "$origin_dir/../rtl/imports/ip001_uart/uart_rx.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/ip001_uart/uart_top.v"]"\
 "[file normalize "$origin_dir/../rtl/imports/ip001_uart/uart_tx.v"]"\
 "[file normalize "$origin_dir/../rtl/sources_1/ip/ila_bp_uart/ila_bp_uart.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
# set files [list \
 # "[file normalize "$origin_dir/../prj/fos_a7_optic_fpga/fos_a7_optic_fpga.srcs/sources_1/bd/design_1/design_1.bd"]"\
 # "[file normalize "$origin_dir/../prj/fos_a7_optic_fpga/fos_a7_optic_fpga.srcs/sources_1/imports/hdl/design_1_wrapper.v"]"\
# ]
# set imported_files [import_files -fileset sources_1 $files]


source $origin_dir/../tcl/user_top_bd_tcl.tcl

set design_name [get_bd_designs]
make_wrapper -files [get_files $design_name.bd] -top -import



# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../rtl/xuji_wangbiao/RT_LAB_comm_with_MC.edf"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "EDIF" -objects $file_obj

set file "$origin_dir/../rtl/ip/clk_wiz_125m/clk_wiz_125m.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "$origin_dir/../rtl/ip/fifo_512x33_dual_clk/fifo_512x33_dual_clk.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "$origin_dir/../rtl/ip/aurora_8b10b_gtp/aurora_8b10b_gtp.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "$origin_dir/../rtl/sources_1/ip/flash_fifo_8192X8/flash_fifo_8192X8.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "$origin_dir/../rtl/xuji_wangbiao/RT_LAB_comm_with_MC.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../rtl/ip/dpram_w512x32_r2048x8/dpram_w512x32_r2048x8.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "user_top" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../rtl/st_lc_fpga_top.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../rtl/st_lc_fpga_top.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "user_top" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a15tcsg325-2 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a15tcsg325-2" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a15tcsg325-2 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a15tcsg325-2" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:$project_name"
